# Generated by Django 5.2.8 on 2025-11-19 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
    ]
