# Generated by Django 5.2.8 on 2025-11-20 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=250)),
                ('book_description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=150)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('last_edition', models.DateField()),
                ('ISBN', models.CharField(help_text='20 caracteres', max_length=20, unique=True)),
                ('page_count', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('cover_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='link da capa')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('RESERVED', 'Reserved')], default='AVAILABLE')),
                ('estoque', models.PositiveIntegerField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author')),
            ],
        ),
    ]
